2021-09-19 14:50:45,960 INFO    MainThread:4600 [wandb_setup.py:_flush():69] setting env: {'entity': 'rishanthrajendhran', 'project': 'eigengame', 'sweep_id': 'x307k8uk', 'root_dir': '/Users/rishanthrajendhran/Desktop/EigenGame', 'run_id': 'qe9bqifj', 'sweep_param_path': '/Users/rishanthrajendhran/Desktop/EigenGame/wandb/sweep-x307k8uk/config-qe9bqifj.yaml'}
2021-09-19 14:50:45,960 INFO    MainThread:4600 [wandb_setup.py:_flush():69] setting login settings: {}
2021-09-19 14:50:45,961 INFO    MainThread:4600 [wandb_init.py:_log_setup():336] Logging user logs to /Users/rishanthrajendhran/Desktop/EigenGame/wandb/run-20210919_145045-qe9bqifj/logs/debug.log
2021-09-19 14:50:45,961 INFO    MainThread:4600 [wandb_init.py:_log_setup():337] Logging internal logs to /Users/rishanthrajendhran/Desktop/EigenGame/wandb/run-20210919_145045-qe9bqifj/logs/debug-internal.log
2021-09-19 14:50:45,961 INFO    MainThread:4600 [wandb_init.py:init():369] calling init triggers
2021-09-19 14:50:45,961 INFO    MainThread:4600 [wandb_init.py:init():376] wandb.init called with sweep_config: {'isSymmetric': True, 'learningRate': 0.9, 'tolerance': 1, 'variant': 'a'}
config: {'xDim': (3, 7), 'numIterations': 10000, 'numStepsPerIteration': 100, 'k': 3, 'learningRate': 1, 'flags': ['-repeatedEVtest'], 'isSymmetric': False, 'variant': 'a', 'tolerance': 10}
2021-09-19 14:50:45,961 INFO    MainThread:4600 [wandb_init.py:init():418] starting backend
2021-09-19 14:50:45,961 INFO    MainThread:4600 [backend.py:_multiprocessing_setup():72] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2021-09-19 14:50:45,975 INFO    MainThread:4600 [backend.py:ensure_launched():132] starting backend process...
2021-09-19 14:50:45,986 INFO    MainThread:4600 [backend.py:ensure_launched():137] started backend process with pid: 4610
2021-09-19 14:50:45,990 INFO    MainThread:4600 [wandb_init.py:init():423] backend started and connected
2021-09-19 14:50:45,994 INFO    MainThread:4600 [wandb_run.py:_config_callback():787] config_cb None None {'isSymmetric': True, 'learningRate': 0.9, 'tolerance': 1, 'variant': 'a'}
2021-09-19 14:50:45,995 INFO    MainThread:4600 [wandb_init.py:init():465] updated telemetry
2021-09-19 14:50:45,995 INFO    MainThread:4600 [wandb_init.py:init():484] communicating current version
2021-09-19 14:50:47,298 INFO    MainThread:4600 [wandb_init.py:init():489] got version response upgrade_message: "wandb version 0.12.2 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2021-09-19 14:50:47,298 INFO    MainThread:4600 [wandb_init.py:init():497] communicating run to backend with 30 second timeout
2021-09-19 14:50:47,691 INFO    MainThread:4600 [wandb_init.py:init():522] starting run threads in backend
2021-09-19 14:50:52,696 INFO    MainThread:4600 [wandb_run.py:_console_start():1565] atexit reg
2021-09-19 14:50:52,697 INFO    MainThread:4600 [wandb_run.py:_redirect():1412] redirect: SettingsConsole.REDIRECT
2021-09-19 14:50:52,697 INFO    MainThread:4600 [wandb_run.py:_redirect():1417] Redirecting console.
2021-09-19 14:50:52,699 INFO    MainThread:4600 [wandb_run.py:_redirect():1479] Redirects installed.
2021-09-19 14:50:52,699 INFO    MainThread:4600 [wandb_init.py:init():546] run started, returning control to user process
2021-09-19 14:50:52,701 INFO    MainThread:4600 [wandb_run.py:_atexit_cleanup():1535] got exitcode: 1
2021-09-19 14:50:52,702 INFO    MainThread:4600 [wandb_run.py:_restore():1507] restore
2021-09-19 14:50:59,709 INFO    MainThread:4600 [wandb_run.py:_wait_for_finish():1657] got exit ret: None
2021-09-19 14:51:01,310 INFO    MainThread:4600 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
}
pusher_stats {
}

2021-09-19 14:51:01,697 INFO    MainThread:4600 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 865
  total_bytes: 865
}

2021-09-19 14:51:02,143 INFO    MainThread:4600 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 865
  total_bytes: 15570
}

2021-09-19 14:51:02,941 INFO    MainThread:4600 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 15570
  total_bytes: 15570
}

2021-09-19 14:51:03,051 INFO    MainThread:4600 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 15570
  total_bytes: 15570
}

2021-09-19 14:51:03,155 INFO    MainThread:4600 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 15570
  total_bytes: 15570
}

2021-09-19 14:51:03,260 INFO    MainThread:4600 [wandb_run.py:_wait_for_finish():1657] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 15570
  total_bytes: 15570
}

2021-09-19 14:51:04,717 INFO    MainThread:4600 [wandb_run.py:_show_files():1879] logging synced files
